### ISSUE TITLE
WTFPL is unacceptable in some corporations

### ISSUE THREAD

**Issue by blackgnezdo** [paulrouget/dzslides#122]
Just wanted to let you know that some companies can't use the code under this license. It is also not approved by OSI.

If it is still an option to dual license, it would be an improvement. I understand that getting all the contributors to agree to this is a challenge.

**Comment by paulrouget** [comment]
Keeping this license because it's cool.

**Comment by 9999years** [comment]
Lawyers [have concurred](https://news.ycombinator.com/item?id=8104407) that the WTFPL is dangerous, legally:

> First, the [WTFPL] license grant is clearly ambiguous. Most license grants are written in terms of exclusive rights of copyright (ie reproduction, derivative work creation, public performance). This one isn't. "Do whatever the fuck you want' is unclear as to exactly what rights you can exercise and can't, because "whatever you want" can be found to not literally be "whatever" (and in fact, when most people say "you can do whatever you want", they often mean "whatever you want within reason")
> 
> Maybe a judge will agree with "it means all of them", maybe they won't. It depends on the situation. I wouldn't want to bet my life on it. Damages would likely be minimal in such a case, except in places with high statutory damages awards. You might get enjoined from using it.
> 
> Second, As for reassigning copyright, probably not. In most jurisdictions, this requires a specific signed instrument.
> 
> Third, you can't put it under a new license and sue the creator, they also have rights to it.
> 
> Fourth, "You have a good point that this is something many people would want. Do you know in which jurisdictions this is actually needed? I wasn't able to find any sources for this."
> 
> At the *very* least, in the US it's a very bad idea not to disclaim warranties. Particularly since people are making warranties on mailing lists as to fitness, etc, all the time.
> 
> I can't stress enough how dangerous it is to not disclaim warranties in the US.
> 
> > Has it been challenged before in a legal sense? Has a lawyer reviewed it? Excellent points."
> 
> OSI declined to name it an open source license, considering it mostly duplicative of others.
> 
> I specifically try to push people to avoid it, and the company i work for won't distribute software that uses it.

Lawyer Dana Schulz [agreed with this assessment on Quora](https://www.quora.com/The-WTFPL-license-seems-like-a-great-license-to-use-as-it-gives-full-freedom-Why-are-there-some-people-that-oppose-this-license/answer/Dana-H-Shultz).

You can read a bit more about how dangerous it is to not disclaim warranty in the US [here](https://cubicspot.blogspot.com/2017/04/wtfpl-is-harmful-to-software-developers.html).

What rights do you want, here? If you want to release to the public domain, [CC0](https://creativecommons.org/publicdomain/zero/1.0/) is probably closest to what you want. Alternatively, the [MIT License](https://opensource.org/licenses/MIT) is widely accepted and well-understood.  If preventing corporate use is your *goal*, which I can certainly respect, then use the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html), which is notoriously difficult to comply with commercially and entirely banned at many companies (a CC non-commercial license would likely do the trick as well). But by keeping the WTFPL you open yourself to somewhat-unknown legal troubles and discourage use of your software.

**Comment by paulrouget** [comment]
You guys aren't fun. I'll take the risk.
