### ISSUE TITLE
broken URL for demo video: videos-cdn.mozilla.net → videos.cdn.mozilla.net

### ISSUE THREAD

**Issue by jonassmedegaard** [paulrouget/dzslides#126]
Hi,

The demo of embedding video into the sliieshow has a URL where hostname is wrong:

Work if replacing videos-cdn.mozilla.net with videos-cdn.mozilla.net (i.e. dot not dash).

**Comment by paulrouget** [comment]
Where is the dot?

**Comment by jonassmedegaard** [comment]
Quoting Paul Rouget (2017-10-30 03:59:35)
> Where is the dot?

Between "videos" and "cdn"

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by paulrouget** [comment]
Thank you.
